// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_A4C_eFE70sOCIRljvpa0_cpNlMlwaK4',
    appId: '1:587561332021:web:2a0670d02e71d5a44e707c',
    messagingSenderId: '587561332021',
    projectId: 'e-commerce-e266c',
    authDomain: 'e-commerce-e266c.firebaseapp.com',
    storageBucket: 'e-commerce-e266c.appspot.com',
    measurementId: 'G-KDR7M38XP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvCInhVVcDsK54GIES8jhVFq2nhY6w52w',
    appId: '1:587561332021:android:9ddffc1a186cb9f14e707c',
    messagingSenderId: '587561332021',
    projectId: 'e-commerce-e266c',
    storageBucket: 'e-commerce-e266c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKtFsT4TwYQlX_QTia-uQytn8hUhb7gLs',
    appId: '1:587561332021:ios:30f75eef8e93324e4e707c',
    messagingSenderId: '587561332021',
    projectId: 'e-commerce-e266c',
    storageBucket: 'e-commerce-e266c.appspot.com',
    iosBundleId: 'com.example.eCommarce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKtFsT4TwYQlX_QTia-uQytn8hUhb7gLs',
    appId: '1:587561332021:ios:776eb9a86de9866d4e707c',
    messagingSenderId: '587561332021',
    projectId: 'e-commerce-e266c',
    storageBucket: 'e-commerce-e266c.appspot.com',
    iosBundleId: 'com.example.eCommarce.RunnerTests',
  );
}
